name: Keep Supabase Alive

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Postgres Client
        run: sudo apt-get install -y postgresql-client

      - name: Ping Database
        env:
            PGPASSWORD: ${{ secrets.DBT_PASSWORD }}
            DB_HOST: ${{ secrets.DBT_HOST }}
            DB_USER: ${{ secrets.DBT_USER }}
        run: |
          # Simple query to wake the DB
          psql -h "$DB_HOST" -U "$DB_USER" -d postgres -p 6543 -c "SELECT 1;"